name: Django CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: yourdbname
          POSTGRES_USER: youruser
          POSTGRES_PASSWORD: yourpassword
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: check postgresservicestatus
      run: ps aux | grep postgres    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        DATABASE_URL: postgres://youruser:yourpassword@127.0.0.1:5432/yourdbname
        DB_NAME: yourdbname
        DB_USER: youruser
        DB_PASSWORD: yourpassword
        DB_PORT: 5432
        DB_HOST: localhost
        
      run: |
        python manage.py migrate
       
       

    - name: Run tests
      env:
        DATABASE_URL: postgres://youruser:yourpassword@127.0.0.1:5432/yourdbname
        DB_NAME: yourdbname
        DB_USER: youruser
        DB_PASSWORD: yourpassword
        DB_PORT: 5432
        DB_HOST: localhost
      run: |
        python manage.py test
    - name: Send Email Notification
      uses: softprops/action-gh-release@v1
      with:
        files: /dev/null
        draft: false
        prerelease: false
        tag_name: ${{ github.sha }}
        name: 'Django CI Build Status'
        body: 'Django CI build completed successfully!'
        target_commitish: ${{ github.sha }}
        email: 'info@mint-easy.de'
        name: 'info@mint-easy.de'
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib

