name: Django CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: yourdbname
          POSTGRES_USER: youruser
          POSTGRES_PASSWORD: yourpassword
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: check postgresservicestatus
      run: ps aux | grep postgres    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        DATABASE_URL: postgres://youruser:yourpassword@127.0.0.1:5432/yourdbname
        DB_NAME: yourdbname
        DB_USER: youruser
        DB_PASSWORD: yourpassword
        DB_PORT: 5432
        DB_HOST: localhost
        
      run: |
        python manage.py migrate
       
       

    - name: Run tests
      env:
        DATABASE_URL: postgres://youruser:yourpassword@127.0.0.1:5432/yourdbname
        DB_NAME: yourdbname
        DB_USER: youruser
        DB_PASSWORD: yourpassword
        DB_PORT: 5432
        DB_HOST: localhost
      run: |
        python manage.py test
  
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: 'Django CI Build Status'
        to: 'info@mint-easy.de'
        from: 'info@mint-easy.de'
        body: 'Django CI build completed successfully!'        
